version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ats_postgres
    environment:
      POSTGRES_DB: ats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 