server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
        jdbc:
          time_zone: UTC
  security:
    jwt:
      secret: 4e81cb9a0e9049caa2d39f228db6225a5b2d4fc1d37d45c4bd2922c3b59e58df
      expiration: 86400000 # 24 hours in milliseconds
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  max-age: 3600

logging:
  level:
    org.springframework.security: DEBUG
    com.ats: DEBUG
    org.hibernate: INFO